### ISSUE TITLE
iojs/node 0.12.x install issue when building node-gyp

### ISSUE THREAD

**Issue by redochka** [danielgtaylor/aglio#77]
I am unable to install aglio. See below the interesting part of the output:

```
$ sudo npm install -g aglio
.
.
.
> ws@0.4.31 install /usr/local/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm http 200 https://registry.npmjs.org/utf8/-/utf8-2.0.0.tgz
npm http 200 https://registry.npmjs.org/base64-arraybuffer/-/base64-arraybuffer-0.1.2.tgz
make: entrant dans le répertoire « /usr/local/lib/node_modules/aglio/node_modules/protagonist/build »
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprint.o
make: entrant dans le répertoire « /usr/local/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build »
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprintSourcemap.o
make: quittant le répertoire « /usr/local/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build »
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CSourceAnnotation.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/HTTP.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Section.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Serialize.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeJSON.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeYAML.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Signature.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/snowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/csnowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/UriTemplateParser.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/posix/RegexMatch.o
  AR(target) Release/obj.target/snowcrash/snowcrash.a
  COPY Release/snowcrash.a
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/ByteBuffer.o
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownNode.o
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownParser.o
  AR(target) Release/obj.target/snowcrash/markdownparser.a
  COPY Release/markdownparser.a
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/autolink.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/buffer.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/markdown.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/src_map.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/stack.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_href_e.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_html_e.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html_smartypants.o
  AR(target) Release/obj.target/snowcrash/sundown.a
  COPY Release/sundown.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
In file included from /home/reda/.node-gyp/0.11.4/src/node.h:62:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h: In member function ‘void v8::ReturnValue<T>::Set(uint32_t)’:
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:5810:31: warning: typedef ‘I’ locally defined but not used [-Wunused-local-typedefs]
   typedef internal::Internals I;
                               ^
../src/annotation.cc: In static member function ‘static void protagonist::SourceAnnotation::Init(v8::Handle<v8::Object>)’:
../src/annotation.cc:21:58: warning: ‘static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::InvocationCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)’ is deprecated (declared at /home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:3263) [-Wdeprecated-declarations]
     Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                          ^
../src/annotation.cc:25:61: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Local<v8::Function>)’
     constructor = Persistent<Function>::New(t->GetFunction());
                                                             ^
../src/annotation.cc:25:61: note: candidate is:
In file included from /home/reda/.node-gyp/0.11.4/src/node.h:62:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:5585:4: note: static T* v8::Persistent<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* Persistent<T>::New(Isolate* isolate, T* that) {
    ^
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:5585:4: note:   candidate expects 2 arguments, 1 provided
../src/annotation.cc:26:68: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Persistent<v8::Function>&)’
     exports->Set(String::NewSymbol("SourceAnnotation"), constructor);
                                                                    ^
../src/annotation.cc:26:68: note: candidates are:
In file included from /home/reda/.node-gyp/0.11.4/src/node.h:62:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:2036:8: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>, v8::PropertyAttribute)
   bool Set(Handle<Value> key,
        ^
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:2036:8: note:   no known conversion for argument 2 from ‘v8::Persistent<v8::Function>’ to ‘v8::Handle<v8::Value>’
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:2040:8: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   bool Set(uint32_t index, Handle<Value> value);
        ^
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:2040:8: note:   no known conversion for argument 1 from ‘v8::Local<v8::String>’ to ‘uint32_t {aka unsigned int}’
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> protagonist::SourceAnnotation::NewInstance()’:
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:771:16: error: ‘T* v8::Persistent<T>::operator->() const [with T = v8::Function]’ is private
   V8_INLINE(T* operator->() const) { return val_; }
                ^
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:80:69: note: in definition of macro ‘V8_INLINE’
 #define V8_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                     ^
../src/annotation.cc:40:41: error: within this context
     Local<Object> instance = constructor->NewInstance();
                                         ^
In file included from /home/reda/.node-gyp/0.11.4/src/node.h:62:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h: In static member function ‘static v8::Local<v8::Object> protagonist::SourceAnnotation::WrapSourceAnnotation(const snowcrash::SourceAnnotation&)’:
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:771:16: error: ‘T* v8::Persistent<T>::operator->() const [with T = v8::Function]’ is private
   V8_INLINE(T* operator->() const) { return val_; }
                ^
/home/reda/.node-gyp/0.11.4/deps/v8/include/v8.h:80:69: note: in definition of macro ‘V8_INLINE’
 #define V8_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                     ^
../src/annotation.cc:55:47: error: within this context
     Local<Object> annotationWrap = constructor->NewInstance();
                                               ^
make: *** [Release/obj.target/protagonist/src/annotation.o] Erreur 1
make: quittant le répertoire « /usr/local/lib/node_modules/aglio/node_modules/protagonist/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:103:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/aglio/node_modules/protagonist
gyp ERR! node -v v0.11.4
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by danielgtaylor** [comment]
@redochka this looks very similar to https://github.com/apiaryio/protagonist/issues/34

Basically, right now it looks like one of our dependencies (Protagonist) does not work on Node 0.11.x or Io.js.

**Comment by zdne** [comment]
@danielgtaylor @redochka you are indeed correct, the Protagonist does not support the latest changes to node.js / io.js APIs and as such it works only with node 0.11. The tracking issue for it can be found here https://github.com/apiaryio/protagonist/issues/16. I will see what I can do about it ASAP.

**Comment by Freundschaft** [comment]
same story here on windows 7 pc

**Comment by zdne** [comment]
Guys sorry about this, we are looking into both v0.11+ (io.js) and Windows support, right now.

**Comment by mojotalantikite** [comment]
For anyone looking in the interim, Protagonist has added protagonist-experimental@0.18.7. I just forked aglio and updated to use protagonist-experimental and everything is working fine so far.

**Comment by zdne** [comment]
For the information: I hope we will release `protagonist-experimental` during the course of this week.

**Comment by danielgtaylor** [comment]
I've created an [experimental branch](https://github.com/danielgtaylor/aglio/tree/experimental) and published an experimental version:

```bash
$ sudo npm install -g aglio@experimental
```

Please use that until protagonist releases a stable version.

**Comment by saltmotor** [comment]
The aglio@experimental branch works for me (Node 0.12.0) currently. Thanks.

**Comment by zdne** [comment]
For your information: We have just released stable [Protagonist v0.19.0](https://github.com/apiaryio/protagonist/releases/tag/v0.19.0) that includes support for io.js and node.js v0.12

**Comment by danielgtaylor** [comment]
Aglio 1.18.0 is now released which depends on the latest Protagonist release and supports Node 0.12.x and io.js 1.x. Please let me know if you have any other issues.
